export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  // refreshToken must only travel via httpOnly cookie, never in the request body.
  BODY_NOT_ALLOWED: 'BODY_NOT_ALLOWED',
  // HTTP 409: concurrent race on token rotation (not replay); client must retry.
  TOKEN_ROTATED: 'TOKEN_ROTATED',
  // HTTP 401: replay detected outside grace window; all sessions revoked.
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_SCORE: 'INVALID_SCORE',

  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  RATING_NOT_FOUND: 'RATING_NOT_FOUND',
  SPECIALTY_NOT_FOUND: 'SPECIALTY_NOT_FOUND',

  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  APPOINTMENT_CONFLICT: 'APPOINTMENT_CONFLICT',
  RATING_EXISTS: 'RATING_EXISTS',

  APPOINTMENT_NOT_COMPLETED: 'APPOINTMENT_NOT_COMPLETED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_SCHEDULED_AT: 'INVALID_SCHEDULED_AT',
  DOCTOR_NOT_ASSIGNED: 'DOCTOR_NOT_ASSIGNED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',

  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
